image: centos:7

before_script:
 - yum install -y git make autoconf libtool automake gettext-devel glibc-devel gcc valgrind libasan-static libgcc.i686 glibc-devel.i686

# See http://doc.gitlab.com/ce/ci/yaml/ for documentation.
build/x86-64:
  script:
  - yum install -y gmp-devel
  - ./.bootstrap &&
    ./configure --enable-fat --disable-documentation && make -j4 &&
    make check -j4
  tags:
  - shared
  except:
  - tags
build/x86:
  script:
  - yum install -y gmp-devel.i686
  - ./.bootstrap &&
    PKG_CONFIG_PATH="/usr/lib/pkgconfig/" CFLAGS="-O2 -g -m32" LDFLAGS="-m32" ./configure --build=i686-redhat-linux --enable-fat --disable-documentation && make -j4 &&
    make check -j4
  tags:
  - shared
  except:
  - tags
build/aarch64:
  before_script:
  - /bin/true
  script:
  - ./.bootstrap &&
    ./configure --enable-fat --disable-documentation && make -j4 &&
    make check -j4
  tags:
  - aarch64
  only:
  - branches@gnutls/nettle
  except:
  - tags
build/mini-gmp:
  script:
  - ./.bootstrap &&
    ./configure --disable-documentation --enable-mini-gmp && make -j4 &&
    make check -j4
  tags:
  - shared
  except:
  - tags
build/ubsan:
  image: fedora:26
  script:
  - yum install -y gmp-devel libubsan-static libubsan
  - ./.bootstrap && 
    CXXFLAGS="-fsanitize=undefined -fno-sanitize-recover -g -O2" CFLAGS="-fsanitize=undefined -fno-sanitize-recover -g -O2" ./configure 
    --disable-documentation && make -j4 && make check -j4
  tags:
  - shared
  except:
  - tags
build/asan:
  image: fedora:26
  script:
  - yum install -y gmp-devel
  - ./.bootstrap && 
  - CXXFLAGS="-fsanitize=address -g -O2" CFLAGS="-fsanitize=address -g -O2" ./configure --disable-documentation &&
    make -j4 && make check -j4
  tags:
  - shared
  except:
  - tags
build/static-analyzers:
  image: fedora:26
  script:
  - yum install -y gmp-devel clang compiler-rt cppcheck clang-analyzer
  - ./.bootstrap
  - scan-build ./configure --disable-documentation
  - scan-build --status-bugs -o scan-build-lib make -j$(nproc)
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - scan-build-lib/*

